jwt-authenticator/config/routes.rb
Rails.application.routes.draw do
  resources :posts

  post 'auth' => 'auth#authenticate'
  root 'home#index'
  get '/logout' => 'home#logout'

end

jwt-authenticator/app/models/auth_token.rb
class AuthToken
  def self.encode(payload, exp=24.hours.from_now)
  	payload[:exp] = exp.to_i
  	JWT.encode(payload, Rails.application.secrets.secret_key_base)
	end

  def self.decode(token)
    payload = JWT.decode(token, Rails.application.secrets.secret_key_base)[0]
    DecodedAuthToken.new(payload)
  rescue
    nil # It will raise an error if it is not a token that was generated with our secret key or if the user changes the contents of the payload
  end

end

jwt-authenticator/app/models/authentication_timeout_error.rb
class AuthenticationTimeoutError < StandardError
end

jwt-authenticator/app/models/decoded_auth_token.rb
class DecodedAuthToken < HashWithIndifferentAccess
  def expired?
    self[:exp] <= Time.now.to_i
  end
end

jwt-authenticator/app/models/not_authenticated_error.rb
class NotAuthenticatedError < StandardError
end

jwt-authenticator/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :users
end

jwt-authenticator/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  def generate_auth_token
    payload = { user_id: self.id }
    AuthToken.encode(payload)
  end
end

jwt-authenticator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user, :authenticate_request

  rescue_from NotAuthenticatedError do
    render json: { error: 'Not Authorized' }, status: :unauthorized
  end
  rescue_from AuthenticationTimeoutError do
    render json: { error: 'Auth token is expired' }, status: 419 # unofficial timeout status code
  end

  private

	  # Based on the user_id inside the token payload, find the user.
	  def set_current_user
	    if decoded_auth_token
	      @current_user ||= User.find(decoded_auth_token[:user_id])
	    end
	  end

	  # Check to make sure the current user was set and the token is not expired
	  def authenticate_request
	    if auth_token_expired?
	      fail AuthenticationTimeoutError
	    elsif !@current_user
	      fail NotAuthenticatedError
	    end
	  end

	  def decoded_auth_token
	    @decoded_auth_token ||= AuthToken.decode(http_auth_header_content)
	  end

	  def auth_token_expired?
	    decoded_auth_token && decoded_auth_token.expired?
	  end

	  # JWT's are stored in the Authorization header using this format:
	  # Bearer somerandomstring.encoded-payload.anotherrandomstring
	  def http_auth_header_content
	    return @http_auth_header_content if defined? @http_auth_header_content
	    @http_auth_header_content = begin
	      if request.headers['Authorization'].present?
	        request.headers['Authorization'].split(' ').last
	      else
	        session[:token]
	      end
	    end
	  end
end

jwt-authenticator/app/controllers/auth_controller.rb
class AuthController < ApplicationController
  skip_before_action :authenticate_request # this will be implemented later
  def authenticate
    user = User.find_by(user_params) # you'll need to implement this
    if user
      token = session[:token] = user.generate_auth_token
      redirect_to posts_path
    else
      render json: { error: 'Invalid username or password' }, status: :unauthorized
    end
  end

  private
    def user_params
      { username: params[:username], password: params[:password]}
    end
end

jwt-authenticator/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_request # this will be implemented later
  def index
    redirect_to posts_path if @current_user
  end

  def logout
    @current_user = session[:token] = nil
    redirect_to root_path
  end
end

jwt-authenticator/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(user_id: @current_user.id)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :user_id)
    end
end

jwt-authenticator/app/helpers/application_helper.rb
module ApplicationHelper
end

jwt-authenticator/app/helpers/posts_helper.rb
module PostsHelper
end

jwt-authenticator/app/views/home/index.html.erb
<%= form_tag('/auth', method: 'post') do  %>
  <div class="container">
    <div class="row">
      <div class = "col-md-12">
        <div class="container login-container" id="formContainer">
          <h3 class="form-signin-heading">Login</h3>
          <%= text_field_tag :username, nil, :class => 'form-control', :placeholder => 'Username'  %>
          <br/>
          <%= password_field_tag :password, nil, :class => 'form-control', :placeholder => 'Password' %>
          <br/>
          <%= submit_tag "Login", :class => 'btn btn-lg btn-primary btn-block' %>
        </div> <!-- /container -->
      </div>
    </div>
  </div>
<% end %>

jwt-authenticator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Posters</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <ul class="nav navbar-nav">
    <li class="active"><a href="#">Json Web Authentication <span class="sr-only">(current)</span></a></li>
      <% if @current_user %>
        <li><%= link_to 'Posts', posts_path %></li>
        <li> <%= link_to "Welcome #{ @current_user.username }" %></li>
        <li> <%= link_to "Logout", logout_path %></li>
      <% else %>
        <li><%= link_to 'Login', root_path %></li>
      <% end %>
  </ul>
</nav>
<%= yield %>

</body>
</html>

jwt-authenticator/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="row">
      <div class = "col-md-12">
        <div class="container login-container" id="formContainer">
          <div class="field">
            <%= f.label :title %><br>
            <%= f.text_field :title, :class => 'form-control' %>
          </div>
          <div class="actions">
            <%= f.submit 'Submit', :class => 'btn btn-lg btn-primary btn-block' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

jwt-authenticator/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

jwt-authenticator/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class = container>
  <div class = "row">
    <div class = "col-md-12">
      <div class = "container post-container">
      <h1>Listing Posts</h1>
      <table class="table table-hover table-bordered">
        <tr>
          <td>Id</td>
          <td>Title</td>
          <td>Edit</td>
          <td>Delete</td>
        </tr>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.user_id %></td>
            <td><%= post.title %></td>
            <td><%= link_to 'Edit', edit_post_path(post), :class => 'btn btn-primary btn-success' %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-primary btn-danger' %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>
<br/>
<%= link_to 'New Post', new_post_path %>

jwt-authenticator/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

jwt-authenticator/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>